matrix:
  include:
    - language: node_js
      script: npm run test
      before_install:
        - npm i -g jest-cli
      node_js:
        - "stable"
    # - language: objective-c
    #   os: osx
    #   osx_image: xcode8.3
    #   script:
    #     - brew update
    #     - brew install nvm
    #     - nvm install 8.4.0
    #     - npm install
    #     - cd ios && xcodebuild -scheme Buttercup -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' build test
    - language: java
      jdk: oraclejdk8
      script:
        - pwd
        - ls -lah
        - ./android/.gradlew assemble
        - ./scripts/testAndroid.sh
